fc=100000;
fs=1000000;
f=1000;
m=.5;
A=1/m;
opt=-A;
t=0:1/fs:((4/f)-(1/fs));
x=cos(2*pi*f*t);
y=modulate(x,fc,fs,'amdsb-tc',opt);
y_n=awgn(y,'measured');
subplot(321),plot(y_n),title('DSB-C modulation,mod. index=0.5,AWGN 20 dB');
x_s=demod(y_n,fc,fs,'amdsb-tc',opt);
subplot(323),plot(x_s),title('DSB-C demodulation,synchronous,AWGN 20 dB');
x_e=envdet_my(y_n,f,fs);
subplot(325),plot(x_e),title('DSB-C demodulation,envelop det.,AWGN 20 dB');
y_n=awgn(y,5,'measured');
subplot(322),plot(y_n),title('DSB-C modulation,mod. index=0.5,AWGN 5 dB');
x_s=demod(y_n,fc,fs,'amdsb-tc',opt);
subplot(324),plot(x_s),title('DSB-C demodulation,synchronous,AWGN 5 dB');
x_e=envdet_my(y_n,f,fs);
subplot(326),plot(x_e),title('DSB-C demodulation,envelop det.,AWGN 5 dB');